package com.github.ozsie

const val HELP = "-h"
const val CREATE_BASELINE = "-cb"
const val DEBUG = "--debug"
const val DISABLE_DEFAULT_RULE_SET = "-dd"
const val GENERATE_CONFIG = "-gc"
const val PARALLEL = "--parallel"
const val BASELINE = "-b"
const val CONFIG = "-c"
const val CONFIG_RESOURCE = "-cr"
const val FILTERS = "-f"
const val INPUT = "-i"
const val OUTPUT = "-o"
const val OUTPUT_NAME = "-on"
const val PLUGINS = "-p"