name: Deploy
on:
  release:
    types: [ published ]

jobs:
  release:
    name: Release on Sonatype OSS
    runs-on: ubuntu-latest
    env:
      MAVEN_OPTS: --add-opens=java.base/java.util=ALL-UNNAMED --add-opens=java.base/java.lang.reflect=ALL-UNNAMED --add-opens=java.base/java.text=ALL-UNNAMED --add-opens=java.desktop/java.awt.font=ALL-UNNAMED

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 25 and Maven Central
        uses: actions/setup-java@v4
        with:
          java-version: 25
          distribution: 'temurin'
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
          cache: 'maven'

      - name: Build and Publish
        run: mvn -B deploy -DperformRelease=true -Ddetekt.skip
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}